/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "CALC.h"

bool_t
xdr_dupla_int (XDR *xdrs, dupla_int *objp)
{
	register int32_t *buf;

	 /* Codifica o decodifica el primer valor (a) */
	if (!xdr_double (xdrs, &objp->a))
		return FALSE;

	/* Codifica o decodifica el segundo valor (b) */
	if (!xdr_double (xdrs, &objp->b))
		return FALSE;

	/* Si ambas conversiones fueron exitosas */
	return TRUE;
}
