/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dupla_int {
	double a;
	double b;
};
typedef struct dupla_int dupla_int;

#define CALC_PROG 0x41111111
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  double * suma_1(dupla_int *, CLIENT *);
extern  double * suma_1_svc(dupla_int *, struct svc_req *);
#define RESTA 2
extern  double * resta_1(dupla_int *, CLIENT *);
extern  double * resta_1_svc(dupla_int *, struct svc_req *);
#define MULTIPLICACION 3
extern  double * multiplicacion_1(dupla_int *, CLIENT *);
extern  double * multiplicacion_1_svc(dupla_int *, struct svc_req *);
#define DIVISION 4
extern  double * division_1(dupla_int *, CLIENT *);
extern  double * division_1_svc(dupla_int *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  double * suma_1();
extern  double * suma_1_svc();
#define RESTA 2
extern  double * resta_1();
extern  double * resta_1_svc();
#define MULTIPLICACION 3
extern  double * multiplicacion_1();
extern  double * multiplicacion_1_svc();
#define DIVISION 4
extern  double * division_1();
extern  double * division_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dupla_int (XDR *, dupla_int*);

#else /* K&R C */
extern bool_t xdr_dupla_int ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
